# Generated by Django 5.2.8 on 2025-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Contact Us', max_length=150)),
                ('sub_heading', models.CharField(default="We're here to help you.", max_length=300)),
                ('map_embed_url', models.TextField(help_text='Paste Google Map Embed URL')),
                ('form_title', models.CharField(default='Send a Message', max_length=150)),
                ('name_placeholder', models.CharField(default='Your Name', max_length=100)),
                ('email_placeholder', models.CharField(default='Your Email', max_length=100)),
                ('message_placeholder', models.CharField(default='Your Message', max_length=150)),
                ('submit_text', models.CharField(default='Send Message', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_icon',
            field=models.CharField(default='bx bx-map', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_icon',
            field=models.CharField(default='bx bx-envelope', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_icon',
            field=models.CharField(default='bx bx-phone-call', max_length=50),
        ),
    ]
